In [1]:
import numpy as np


In [2]:
l=[1,2,3,4]

In [3]:
arr=np.array(l)
arr

array([1, 2, 3, 4])

In [4]:
arr.shape

(4,)

In [6]:
l=[[1,2,3],[4,5,6],[7,8,9]]
mul=np.array(l)
print(mul)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
mul.shape

(3, 3)

In [15]:
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [20]:
np.empty((2,3))

array([[4.84716997e-310, 0.00000000e+000, 7.06764524e-096],
       [7.06743455e-096, 7.19081964e+140, 6.92980169e-310]])

In [22]:
np.full(6,5)

array([5, 5, 5, 5, 5, 5])

In [27]:
arr=np.arange(0,15)
print(arr)
arr.reshape(3,5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
np.random.rand(5,6)

array([[0.99276527, 0.18431633, 0.76474536, 0.16777692, 0.20719124,
        0.54658993],
       [0.41645364, 0.39766239, 0.4643057 , 0.54156902, 0.26513711,
        0.59813354],
       [0.17605679, 0.96986236, 0.17690018, 0.15543272, 0.27570903,
        0.38087512],
       [0.95071556, 0.91481517, 0.16604883, 0.2164903 , 0.00698324,
        0.64108217],
       [0.69356947, 0.09628076, 0.59729498, 0.11078215, 0.5032842 ,
        0.24053632]])

In [30]:
np.random.randn(5,6)

array([[ 0.63173985,  0.27911225,  1.17357315, -0.74924133,  1.11420139,
         1.4496917 ],
       [-1.29875052, -1.32918836,  0.32104431, -0.73350392,  0.8198466 ,
        -1.09236605],
       [-0.78223535, -0.280926  ,  0.51211166,  1.31239413, -0.04344986,
         0.05613895],
       [-1.20598861, -0.42642587,  1.52656001, -0.05599967,  1.66593831,
        -0.81734252],
       [-2.25717223, -0.72403374, -0.22829148, -0.33158193, -2.30261518,
         0.34176379]])

In [35]:
x=np.random.randint(1,100,10)
x

array([ 1, 49, 39, 47, 58, 36, 45, 33, 26, 16])

In [38]:
print(x.max())
print(x.min())
print(x.argmax())

58
1
4


In [39]:
arr=np.arange(50)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [43]:
slice=arr[1:5]
slice

array([100, 100, 100, 100])

In [44]:
slice[:]=100

In [45]:
print(slice)


[100 100 100 100]


In [46]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49])

In [47]:
arr_copy=arr.copy()
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49])

In [48]:
sli=arr_copy[10:20]
sli

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
sli[:]=500

In [50]:
sli

array([500, 500, 500, 500, 500, 500, 500, 500, 500, 500])

In [52]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49])

In [53]:
array=np.arange(50)

In [54]:
array.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [59]:
arra=np.array([[5,10,15],[20,25,30],[35,40,45]])
print(arra)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [61]:
arra[1][1]

25

In [62]:
arra[1]

array([20, 25, 30])

In [63]:
arra[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [64]:
arra[1:,1:]

array([[25, 30],
       [40, 45]])

In [65]:
a=np.arange(11)

In [66]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
a>5


array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [72]:
a[a<=5]

array([0, 1, 2, 3, 4, 5])

In [73]:
y=np.arange(50)

In [74]:
y.shape

(50,)

In [78]:
yy=y.reshape(5,10)
yy

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [79]:
yy[1:3,3:5]


array([[13, 14],
       [23, 24]])

In [80]:
yy[1:4,1:6]

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

In [83]:
arr=np.random.randint(1,100,10)
arr

array([ 3, 67, 51, 11, 58, 39, 99, 67,  5,  4])

In [86]:
arr1=np.arange(11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
arr1+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [87]:
arr1*10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [88]:
arr1-500

array([-500, -499, -498, -497, -496, -495, -494, -493, -492, -491, -490])

In [90]:
arr1/arr1

<ipython-input-90-f958b1cc4b79>:1: RuntimeWarning: invalid value encountered in divide
  arr1/arr1


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [91]:
1/arr1

<ipython-input-91-0dda6b58807b>:1: RuntimeWarning: divide by zero encountered in divide
  1/arr1


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [92]:
arr**2

array([   9, 4489, 2601,  121, 3364, 1521, 9801, 4489,   25,   16])

In [93]:
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [94]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
np.log(arr)

array([1.09861229, 4.20469262, 3.93182563, 2.39789527, 4.06044301,
       3.66356165, 4.59511985, 4.20469262, 1.60943791, 1.38629436])

In [96]:
np.sin(arr)

array([ 0.14112001, -0.85551998,  0.67022918, -0.99999021,  0.99287265,
        0.96379539, -0.99920683, -0.85551998, -0.95892427, -0.7568025 ])

In [98]:
np.tanh(arr)

array([0.99505475, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.9999092 , 0.9993293 ])

In [99]:
np.max(arr1)

10

In [101]:
np.argmax(arr1)

10

In [104]:
##numpy exercise


#numpy exercises

In [105]:
import numpy as np

In [106]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [107]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [110]:
np.full(10,5,dtype=float)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [111]:
arrint=np.arange(10,51)
arrint

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [112]:
arrev=np.arange(10,51,2)
arrev

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [113]:
mat=np.arange(0,9)

In [114]:
mat.shape

(9,)

In [115]:
matrix=mat.reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [116]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [119]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [125]:
np.random.rand(1,1)

array([[0.55038816]])

In [127]:
np.random.randn(25)

array([ 0.27328177, -0.21416826, -0.86551405,  0.18902372,  1.16126985,
       -3.40297203, -0.27237559,  1.19182244, -0.58421328,  0.65971167,
       -0.86787783,  0.46900658, -1.30025139,  1.72238841,  0.58378987,
        0.51863705, -0.57938263, -0.35625426, -0.91505506, -1.04612638,
       -1.28936042, -0.4219981 , -0.34324578,  1.33110931, -0.51247212])

In [137]:
r=np.arange(0.01,1.01,0.01)
r

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [138]:
r.shape

(100,)

In [139]:
r.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [140]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [141]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [145]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [146]:
mat[3,4]

20

In [150]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [151]:
mat[4]

array([21, 22, 23, 24, 25])

In [152]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [153]:
np.sum(mat)

325

In [155]:
np.sum(mat[0:])

325

In [156]:
np.std(mat)

7.211102550927978

In [159]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])